### ISSUE TITLE
Footer Bar - OS X Ghosting

### ISSUE THREAD

**Issue by THEY** [MarkHMorrison/nexus-theme#1]
Great theme! 

But there appears to be some ghosting in the footer bar in OS X.

I think the "ghosts" are the other tab's prior messages/states.

Take a look here:  http://imgur.com/701kn

---

Actually just changing line 377 to:

```
 "layer0.opacity": 1,
```

from:

```
"layer0.opacity": 0.8,
```

worked on solving the issue.

**Comment by MarkHMorrison** [comment]
Thanks.

I'll have to look into it later this week.  I appreciate the feedback.

At your service,

Mark H. Morrison

On Aug 29, 2012, at 12:50 PM, Chris Yeoh notifications@github.com wrote:

Great theme!

But there appears to be some ghosting in the footer bar in OS X.

I think the "ghosts" are the other tab's prior messages/states.

Take a look here: http://imgur.com/701kn
