### ISSUE TITLE
ST3 build 3062 - Too much indent for files under a folder

### ISSUE THREAD

**Issue by Jackbennett** [MarkHMorrison/nexus-theme#13]
Hi, Just installed the theme through package install to fix this issue I'm having with some other themes too.
## Default theme sidebar

![sublime - sidebar indent - default](https://cloud.githubusercontent.com/assets/791134/3171390/e39de610-ebc5-11e3-99e3-90069102e795.PNG)
## Flatron

![sublime - sidebar indent - flatron](https://cloud.githubusercontent.com/assets/791134/3171396/fd950ec2-ebc5-11e3-87cd-33b34895ad95.PNG)
## Suggestions
- It looks to me like flatron is missing icons for the files but still preserving the indent space.
- Is the default theme now using 2 icons, one for the folder type and one for the expanded/condensed states where flatland is using one for both and leaving space?

I quite like having no icons on files but the space is a huge problem, files in their parent look as though they are contained within their child folders.

**Comment by LOQUILLO** [comment]
Hi @Jackbennett look this:

![nexus-icons-full](https://cloud.githubusercontent.com/assets/1308190/5363407/ed3d5e08-7fa9-11e4-878a-fa9c11785d0b.jpg)
![nexus-icons-full-2](https://cloud.githubusercontent.com/assets/1308190/5363416/fb162ab4-7fa9-11e4-92a7-421d55072997.jpg)
![nexus-icons-full-3](https://cloud.githubusercontent.com/assets/1308190/5363422/039ec0ce-7faa-11e4-8849-9d029e603d41.jpg)

It's Nexus modified by me.

**Comment by LOQUILLO** [comment]
Look this other;
![nexus-icons-folder](https://cloud.githubusercontent.com/assets/1308190/5363477/66526428-7faa-11e4-939e-9ea10addbe49.jpg)

**Comment by Doskious** [comment]
To correct this without adding file icons, I believe that all that is necessary is to add

```
//  - Hide original file icon space
{
    "class": "icon_file_type",
    "content_margin": [0,0]
},
```

to the Nexus.sublime-theme file, as of ST3 Build 3083.  Not sure how this would fare in earlier builds or ST2.

**Comment by gertjanwytynck** [comment]
@LOQUILLO

Can you share you Theme? Looks nice.

**Comment by Jackbennett** [comment]
2 Solid suggestions there. In the end I got an icon pack before I saw these replies but thanks to Doskious I'll use that change to clean up the sidebar. For most of the last year I've moved to brackets.

**Comment by LOQUILLO** [comment]
Hi @gertjanwytynck here is your gift:
https://github.com/LOQUILLO/Theme-Nexus
It was uploaded for you, only.

**Comment by gertjanwytynck** [comment]
Awesome! Santa is early this year. TY!
