### ISSUE TITLE
Support ST3

### ISSUE THREAD

**Issue by felipe-prenholato** [MarkHMorrison/nexus-theme#6]
Hello. This is the theme I love, however it not works in Sublime Text 3 builds.

Can you fix errors?

**Comment by craig-jennings** [comment]
What errors are you seeing? I just installed this theme with ST3 and there were no problems.

**Comment by natecox** [comment]
I'm not getting any errors per say, but I am seeing minor breakages on the nightly from ST3. 

First thing that comes to mind is the tab switcher arrows at the top left of the open file.

**Comment by Raynos** [comment]
:+1: Can you add it to ST3 package control ?

**Comment by willvoutier** [comment]
I am getting this visual issue in ST3 when opening the command palette: 
![screen shot 2013-08-20 at 9 59 50 am](https://f.cloud.github.com/assets/1755752/994219/384d9df4-09a9-11e3-9aab-91f2fcedabd8.png)

**Comment by Raynos** [comment]
I'm getting the same visual issue.

**Comment by steinmb** [comment]
Try also testing your packages at http://www.caniswitchtosublimetext3.com and this theme was tagged as not supporting ST3.

**Comment by LOQUILLO** [comment]
hi @EleazarCrusader you could fix errors and add support for ST3

**Comment by jonstuebe** [comment]
+1 Would love to see ST3 support. What all goes into upgrading the theme. I would be on board with helping.

**Comment by LOQUILLO** [comment]
![nexus_st3](https://cloud.githubusercontent.com/assets/1308190/2833175/acb194ee-cfcd-11e3-81c6-07ef674cdd37.jpg)
![nexus_2_st3](https://cloud.githubusercontent.com/assets/1308190/2833241/69d81930-cfce-11e3-94eb-ba520fc184c9.jpg)

Hi, this theme I have working in ST3 with no issues. I dunno why was givingme errors, but in a fressh and clean installation of ST3 all is working ok. I had fixed little cosmetic bug.

**Comment by LOQUILLO** [comment]
- Download from https://github.com/EleazarCrusader/nexus-theme/archive/master.zip
- Unzip the files and rename the folder to `Theme - Nexus`
- Copy the folder to your ~\Sublime Text 3\Packages\ directory

To configure Sublime Text 3 to use the theme:
- Open your User Settings Preferences file `Sublime Text 3 -> Preferences -> Settings - User`
- Add (or update) your theme entry to be "theme": "Nexus.sublime-theme"

That's all.

**Comment by LOQUILLO** [comment]
This is the changes:
//  PANEL BACKGROUNDS
//  =========================================================
    //  - Bottom panel background
    {
        "class": "panel_control",
        "layer0.texture": "Theme - Nexus/assets/panel-bg.png",
        "layer0.inner_margin": [4, 4, 4, 4],
        "layer0.opacity": 1.0
    },

```
//  - Quick panel background
{
    "class": "overlay_control",
    "layer0.texture": "Theme - Nexus/assets/default/overlay-bg.png",
    "layer0.inner_margin": [10, 5, 10, 10],  // left, top, right, bottom
    "layer0.opacity": 1.0,
    "layer1.opacity": 0, // HIDDEN
    "layer2.opacity": 0,
    "content_margin": [11, 8, 11, 17]
},
```

**Comment by LOQUILLO** [comment]
This is the line fixed:
"layer0.inner_margin": [10, 5, 10, 10],  // left, top, right, bottom

The old is:
"layer0.inner_margin": [10, 5, 10, 20],  // left, top, right, bottom

I had added this line:
"layer2.opacity": 0,

The original Nexus.sublime-theme don't have it

**Comment by LOQUILLO** [comment]
I had tested that put Nexus.sublime-theme file into ~\Sublime Text 3\Packages\User is working all ok, if you wanna to do change to original theme file could it in there.

**Comment by LOQUILLO** [comment]
Hi @chronossc @natecox @Raynos @williamhc @steinmb @jonstuebe, I think that all is fixed now, test my fix.

**Comment by Raynos** [comment]
@LOQUILLO https://github.com/Raynos/nexus-theme/commit/1a676118fc45bc5b58238a29643a99e6ceeb8119

and https://github.com/Raynos/dotfiles/tree/master/.config/sublime-text-3/Packages

I applied your fix to my branch and then installed that package manually in my dotfiles.

I can confirm that it renders properly now.

Thank you very much for the fix!

**Comment by Raynos** [comment]
@LOQUILLO do you want to make a PR on this repo or shall I do it ?

**Comment by Raynos** [comment]
@LOQUILLO btw awesome work :)

**Comment by LOQUILLO** [comment]
Hi @Raynos, you can do it, but don't forget mention me.

**Comment by MarkHMorrison** [comment]
Installed the pull request.  Package control should update on its own.

**Comment by MarkHMorrison** [comment]
Thanks for working on it.  I've been too swamped with life issues to get back into it.

**Comment by LOQUILLO** [comment]
Hi @Raynos which is the next sublime-theme for fix, I have free time for help.

**Comment by Raynos** [comment]
@LOQUILLO I've been trying to get `gitgutter` to colorize properly in my themes.

I had an open comment here https://github.com/jisaacks/GitGutter/issues/118#issuecomment-41774142

I think i have to either update my theme (nexus-theme) or my color theme ( https://github.com/Benvie/JavaScriptNext.tmLanguage ) to have the gitgutter styling. I think it's my color theme that needs updating. Although I think I can try this myself

**Comment by LOQUILLO** [comment]
Hi @Raynos I could post my custom sublime-themes, I personally too, use different color scheme for differents languages, somelike CSS files have his own CSS.tmTheme, HTML file with his own HTML.tmTheme, maybe it can help you for solve gitgutter problems.

**Comment by LOQUILLO** [comment]
Hi @Raynos, GitGutter was working somedays in my ST2 but after, mysteriously anymore, I had disabled JSHint, JSLint, CSSLint, SublimeLinter, but GitGutter never back to work. In these days can try again for fix this issue. You check wich Packages can is blocking GitGutter.
